services:
  phishu:
    image: killbasa/phishu:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./db.sqlite:/etc/phishu/db.sqlite
