name: CI

on:
  pull_request:
    paths-ignore:
      - "**/README.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Rust
        uses: ./.github/actions/setup

      - name: Check
        run: cargo check

      - name: Test
        run: cargo test

      - name: Format
        run: cargo fmt --check

      - name: Lint
        run: cargo clippy -- --deny warnings
